version: '3.1'

services:
  mysql:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: my-secret-pw
        MYSQL_DATABASE: redmine
      volumes:
        - /home/docker/datadir:/var/lib/mysql
      networks:
        - backend
  redmine:
    image: redmine
    restart: always
    ports:
      - 3000:3000
    networks:
      - backend
networks:
  backend:

#docker stack deploy -c stack.yml redmine (or docker-compose -f stack.yml up) 
